version: '3'

services:
  mem0-service:
    build:
      context: .
      dockerfile: Dockerfile.mem0
    ports:
      - "8009:8000"
    environment:
      - MEM0_API_KEY=${MEM0_API_KEY}
      - SUPABASE_URL=http://host.docker.internal:54321
      - SUPABASE_KEY=${SUPABASE_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
