enabled_tools:
- template_tool
tool_settings:
  default_response_format: json
  inherit_from_parent: true
  log_executions: true
  template_tool:
    cache_ttl: 3600
    enable_caching: true
    max_retries: 3
  timeout_seconds: 30
